\LoadClass{qh_global}
\NeedsTeXFormat{LaTeX2e}[1994/06/01]
\ProvidesPackage{qh_exercuise}[q\-highschool exercise style]

% \begin{itemize}
%     \item \myhref{http://www.github.com/StevenBrons/Processing}{GitHub Pagina} 
%     \item \myhref{https://natureofcode.com/book}{Nature of Code boek} 
%     \item \myhref{https://www.youtube.com/user/shiffman/playlists?view=50\&sort=dd\&shelf\_id=2}{Processing Basic tutorial}
% \end{itemize}

\endinput